<?php
namespace App\Http\Controllers\Api;
use App\Domain\Accounting\Actions\ReconcileBankStatement;use App\Http\Controllers\Controller;use App\Models\BankReconciliation;use App\Models\BankStatementLine;use App\Models\CooperativeBankAccount;use App\Models\JournalEntryLine;use App\Models\LedgerAccount;use App\Support\Security\ProtectedIdentifier;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;
class BankReconciliationController extends Controller{
 public function accounts():JsonResponse{return response()->json(CooperativeBankAccount::query()->with('reconciliations')->get());}
 public function storeAccount(Request $request,ProtectedIdentifier $protector):JsonResponse{$d=$request->validate(['ledger_account_id'=>['required','ulid'],'name'=>['required','string','max:160'],'bank_code'=>['required','string','max:20'],'bank_name'=>['required','string','max:160'],'account_number'=>['required','string','between:6,30'],'currency'=>['sometimes','string','size:3'],'is_active'=>['required','boolean']]);LedgerAccount::query()->findOrFail($d['ledger_account_id']);$protected=$protector->protect($d['account_number']);unset($d['account_number']);return response()->json(CooperativeBankAccount::query()->create([...$d,'account_number_encrypted'=>$protected['encrypted'],'account_number_hash'=>$protected['hash'],'account_number_last_four'=>$protected['last_four']]),201);}
 public function index():JsonResponse{return response()->json(BankReconciliation::query()->with('bankAccount')->latest('statement_end_date')->paginate());}
 public function store(Request $request):JsonResponse{$d=$request->validate(['cooperative_bank_account_id'=>['required','ulid'],'statement_start_date'=>['required','date'],'statement_end_date'=>['required','date','after_or_equal:statement_start_date'],'opening_balance_minor'=>['required','integer'],'closing_balance_minor'=>['required','integer'],'lines'=>['required','array','min:1'],'lines.*.transaction_date'=>['required','date'],'lines.*.reference'=>['nullable','string','max:160'],'lines.*.description'=>['required','string','max:2000'],'lines.*.amount_minor'=>['required','integer','not_in:0'],'lines.*.running_balance_minor'=>['nullable','integer'],'lines.*.external_id'=>['nullable','string','max:160']]);CooperativeBankAccount::query()->findOrFail($d['cooperative_bank_account_id']);$reconciliation=BankReconciliation::query()->create([...collect($d)->except('lines')->all(),'status'=>'draft','prepared_by'=>Auth::id()]);foreach($d['lines'] as $line)$reconciliation->statementLines()->create($line);return response()->json($reconciliation->load('statementLines'),201);}
 public function show(BankReconciliation $reconciliation):JsonResponse{return response()->json($reconciliation->load(['bankAccount','statementLines.matches']));}
 public function match(Request $request,BankStatementLine $statementLine,ReconcileBankStatement $action):JsonResponse{$d=$request->validate(['journal_entry_line_id'=>['required','ulid'],'matched_amount_minor'=>['required','integer','min:1']]);return response()->json($action->match($statementLine,JournalEntryLine::query()->findOrFail($d['journal_entry_line_id']),(int)$d['matched_amount_minor']),201);}
 public function autoMatch(BankReconciliation $reconciliation,ReconcileBankStatement $action):JsonResponse{return response()->json(['matched'=>$action->autoMatch($reconciliation)]);}
 public function complete(BankReconciliation $reconciliation,ReconcileBankStatement $action):JsonResponse{return response()->json($action->complete($reconciliation));}
}
