<?php
namespace App\Http\Controllers\Api;
use App\Domain\Credit\Actions\SaveLoanProduct; use App\Domain\Credit\Services\ChargeCalculator; use App\Domain\Credit\Services\CreditPolicyEvaluator; use App\Domain\Credit\Services\EligibilityEvaluator; use App\Domain\Credit\Services\RepaymentScheduleGenerator; use App\Http\Controllers\Controller; use App\Http\Requests\StoreLoanProductRequest; use App\Models\LoanProduct; use Carbon\CarbonImmutable; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class LoanProductController extends Controller
{
    public function index():JsonResponse{return response()->json(LoanProduct::query()->withCount(['charges','eligibilityRules'])->orderBy('name')->paginate());} public function store(StoreLoanProductRequest $request,SaveLoanProduct $action):JsonResponse{return response()->json($action->execute($request->validated()),201);} public function show(LoanProduct $loanProduct):JsonResponse{return response()->json($loanProduct->load(['charges','eligibilityRules','approvalWorkflow.steps']));} public function update(StoreLoanProductRequest $request,LoanProduct $loanProduct,SaveLoanProduct $action):JsonResponse{return response()->json($action->execute($request->validated(),$loanProduct));} public function destroy(LoanProduct $loanProduct):mixed{$loanProduct->delete();return response()->noContent();}
    public function preview(Request $request,LoanProduct $loanProduct,RepaymentScheduleGenerator $schedules,ChargeCalculator $charges):JsonResponse{$data=$request->validate(['principal_minor'=>['required','integer','min:1'],'tenure'=>['required','integer','min:1'],'start_date'=>['required','date'],'member_category_id'=>['nullable','ulid']]);$schedule=$schedules->generate($loanProduct,(int)$data['principal_minor'],(int)$data['tenure'],CarbonImmutable::parse($data['start_date']));$chargeRows=$charges->calculate($loanProduct,(int)$data['principal_minor'],$data['member_category_id']??null);return response()->json([...$schedule,'charges'=>$chargeRows,'charges_total_minor'=>collect($chargeRows)->sum('amount_minor')]);}
    public function evaluate(Request $request,LoanProduct $loanProduct,EligibilityEvaluator $evaluator):JsonResponse{$data=$request->validate(['facts'=>['required','array']]);return response()->json($evaluator->evaluate($loanProduct,$data['facts']));}
    public function policy(Request $request,LoanProduct $loanProduct,CreditPolicyEvaluator $evaluator):JsonResponse{$data=$request->validate(['requested_principal_minor'=>['required','integer','min:1'],'facts'=>['required','array']]);return response()->json($evaluator->evaluate($loanProduct,(int)$data['requested_principal_minor'],$data['facts']));}
    public function guarantorCapacity(Request $request,LoanProduct $loanProduct,CreditPolicyEvaluator $evaluator):JsonResponse{$data=$request->validate(['facts'=>['required','array']]);return response()->json($evaluator->guarantorCapacity($loanProduct,$data['facts']));}
}
