<?php
namespace App\Http\Controllers\Api;
use App\Domain\Loans\Actions\AddLoanGuarantor;use App\Domain\Loans\Actions\AssessLoanApplication;use App\Domain\Loans\Actions\CreateLoanApplication;use App\Domain\Loans\Actions\DecideLoanApplication;use App\Domain\Loans\Actions\DisburseLoan;use App\Domain\Loans\Actions\SubmitLoanApplication;use App\Http\Controllers\Controller;use App\Models\LoanApplication;use App\Models\LoanApplicationGuarantor;use App\Models\LoanProduct;use App\Models\Member;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;
class LoanApplicationController extends Controller{
 public function index():JsonResponse{return response()->json(LoanApplication::query()->with(['member','product'])->latest()->paginate());}public function show(LoanApplication $loanApplication):JsonResponse{return response()->json($loanApplication->load(['member','product','assessments','guarantors.guarantor','decisions','loan.installments','loan.charges']));}
 public function store(Request $request,Member $member,CreateLoanApplication $action):JsonResponse{$d=$request->validate(['loan_product_id'=>['required','ulid'],'requested_principal_minor'=>['required','integer','min:1'],'tenure'=>['required','integer','min:1'],'purpose'=>['required','string','max:3000'],'preferred_bank_account_id'=>['nullable','ulid']]);return response()->json($action->execute($member,LoanProduct::query()->findOrFail($d['loan_product_id']),$d),201);}
 public function assess(Request $request,LoanApplication $loanApplication,AssessLoanApplication $action):JsonResponse{$d=$request->validate(['start_date'=>['required','date'],'facts'=>['required','array'],'recommendation'=>['nullable','string','max:3000']]);return response()->json($action->execute($loanApplication,$d),201);}public function submit(LoanApplication $loanApplication,SubmitLoanApplication $action):JsonResponse{return response()->json($action->execute($loanApplication));}
 public function decide(Request $request,LoanApplication $loanApplication,DecideLoanApplication $action):JsonResponse{$d=$request->validate(['decision'=>['required','in:approve,reject'],'comment'=>['nullable','string','max:3000']]);return response()->json($action->execute($loanApplication,$d['decision'],$d['comment']??null));}
 public function addGuarantor(Request $request,LoanApplication $loanApplication,AddLoanGuarantor $action):JsonResponse{$d=$request->validate(['guarantor_member_id'=>['required','ulid'],'guaranteed_amount_minor'=>['required','integer','min:1'],'facts'=>['required','array']]);return response()->json($action->execute($loanApplication,Member::query()->findOrFail($d['guarantor_member_id']),$d),201);}public function consent(Request $request,LoanApplicationGuarantor $guarantor,AddLoanGuarantor $action):JsonResponse{$d=$request->validate(['decision'=>['required','in:accepted,rejected']]);return response()->json($action->consent($guarantor,$d['decision']));}
 public function disburse(Request $request,LoanApplication $loanApplication,DisburseLoan $action):JsonResponse{$d=$request->validate(['disbursement_date'=>['required','date'],'currency'=>['sometimes','string','size:3'],'bank_account_id'=>['nullable','ulid']]);return response()->json($action->execute($loanApplication,$d),201);}
}
