<?php
namespace App\Http\Requests;
use App\Enums\InterestMethod; use App\Enums\RepaymentFrequency; use App\Support\Tenancy\TenantContext; use Illuminate\Foundation\Http\FormRequest; use Illuminate\Validation\Rule;
class StoreLoanProductRequest extends FormRequest
{
    public function authorize(): bool{return true;} public function rules(): array{return [
        'name'=>['required','string','max:160'],'code'=>['required','alpha_dash:ascii','max:40',Rule::unique('loan_products')->where('cooperative_id',app(TenantContext::class)->id())->ignore($this->route('loan_product'))],'description'=>['nullable','string','max:2000'],'approval_workflow_id'=>['nullable','ulid',Rule::exists('approval_workflows','id')->where('cooperative_id',app(TenantContext::class)->id())],
        'minimum_principal_minor'=>['required','integer','min:1'],'maximum_principal_minor'=>['required','integer','gte:minimum_principal_minor'],'minimum_tenure'=>['required','integer','min:1'],'maximum_tenure'=>['required','integer','gte:minimum_tenure'],'interest_method'=>['required',Rule::enum(InterestMethod::class)],'annual_interest_rate_basis_points'=>['required','integer','between:0,100000'],'repayment_frequency'=>['required',Rule::enum(RepaymentFrequency::class)],'grace_period_days'=>['required','integer','between:0,365'],'moratorium_periods'=>['required','integer','between:0,60'],
        'requires_guarantors'=>['required','boolean'],'minimum_guarantors'=>['required','integer','between:0,20'],'maximum_guarantors'=>['required','integer','gte:minimum_guarantors','max:20'],'maximum_debt_to_income_basis_points'=>['nullable','integer','between:0,10000'],'contribution_limit_multiplier_basis_points'=>['nullable','integer','min:0'],'savings_limit_multiplier_basis_points'=>['nullable','integer','min:0'],'minimum_membership_months'=>['required','integer','between:0,1200'],'guarantor_maximum_exposure_basis_points'=>['required','integer','min:0'],'guarantor_maximum_active_loans'=>['required','integer','between:0,100'],'allows_early_settlement'=>['required','boolean'],'is_active'=>['required','boolean'],'configuration'=>['nullable','array'],
        'charges'=>['sometimes','array'],'charges.*.charge_id'=>['required','ulid',Rule::exists('charges','id')->where('cooperative_id',app(TenantContext::class)->id())],'charges.*.sequence'=>['required','integer','min:0'],'charges.*.is_mandatory'=>['required','boolean'],'charges.*.overrides'=>['nullable','array'],
        'eligibility_rules'=>['sometimes','array'],'eligibility_rules.*.name'=>['required','string','max:160'],'eligibility_rules.*.field'=>['required','string','max:60'],'eligibility_rules.*.operator'=>['required','in:eq,neq,gt,gte,lt,lte,in,not_in,between'],'eligibility_rules.*.comparison_value'=>['required','array'],'eligibility_rules.*.failure_message'=>['required','string','max:500'],'eligibility_rules.*.is_hard_rule'=>['required','boolean'],'eligibility_rules.*.sequence'=>['required','integer','min:0'],'eligibility_rules.*.is_active'=>['required','boolean'],
    ];}
}
