<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('ledger_accounts',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('parent_id')->nullable()->constrained('ledger_accounts')->nullOnDelete();$t->string('code',30);$t->string('name');$t->string('type',20);$t->string('normal_balance',10);$t->boolean('is_control_account')->default(false);$t->boolean('allows_direct_posting')->default(true);$t->boolean('is_system')->default(false);$t->boolean('is_active')->default(true);$t->text('description')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['cooperative_id','code']);$t->index(['cooperative_id','type','is_active']);});
  Schema::create('accounting_periods',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->string('name');$t->date('start_date');$t->date('end_date');$t->string('status',20)->default('open');$t->foreignUlid('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('closed_at')->nullable();$t->timestamps();$t->unique(['cooperative_id','start_date','end_date'],'accounting_period_tenant_dates_unique');});
  Schema::create('journal_entries',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('accounting_period_id')->constrained()->cascadeOnDelete();$t->foreignUlid('reversal_of_id')->nullable()->constrained('journal_entries')->nullOnDelete();$t->string('reference',100);$t->date('entry_date');$t->string('source_type')->nullable();$t->ulid('source_id')->nullable();$t->string('event_type',80)->nullable();$t->text('description');$t->string('currency',3)->default('NGN');$t->unsignedBigInteger('total_debit_minor');$t->unsignedBigInteger('total_credit_minor');$t->string('status',20)->default('posted');$t->foreignUlid('posted_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('posted_at')->nullable();$t->foreignUlid('reversed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reversed_at')->nullable();$t->text('reversal_reason')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['cooperative_id','reference']);$t->unique(['cooperative_id','source_type','source_id','event_type'],'journal_source_event_unique');$t->index(['cooperative_id','entry_date','status']);});
  Schema::create('journal_entry_lines',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('journal_entry_id')->constrained()->cascadeOnDelete();$t->foreignUlid('ledger_account_id')->constrained()->restrictOnDelete();$t->foreignUlid('member_id')->nullable()->constrained()->nullOnDelete();$t->foreignUlid('loan_id')->nullable()->constrained()->nullOnDelete();$t->foreignUlid('branch_id')->nullable()->constrained()->nullOnDelete();$t->unsignedBigInteger('debit_minor')->default(0);$t->unsignedBigInteger('credit_minor')->default(0);$t->string('memo')->nullable();$t->json('dimensions')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['cooperative_id','ledger_account_id','created_at'],'journal_line_account_date_idx');$t->index(['cooperative_id','member_id']);$t->index(['cooperative_id','loan_id']);});
  Schema::create('accounting_posting_rules',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->string('event_type',80);$t->foreignUlid('debit_account_id')->constrained('ledger_accounts')->restrictOnDelete();$t->foreignUlid('credit_account_id')->constrained('ledger_accounts')->restrictOnDelete();$t->string('description_template')->nullable();$t->json('conditions')->nullable();$t->json('dimensions')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['cooperative_id','event_type']);});
  Schema::create('cooperative_bank_accounts',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('ledger_account_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('bank_code',20);$t->string('bank_name');$t->text('account_number_encrypted');$t->string('account_number_hash',64);$t->string('account_number_last_four',4);$t->string('currency',3)->default('NGN');$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['cooperative_id','bank_code','account_number_hash'],'coop_bank_account_unique');});
  Schema::create('bank_reconciliations',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('cooperative_bank_account_id')->constrained()->cascadeOnDelete();$t->date('statement_start_date');$t->date('statement_end_date');$t->bigInteger('opening_balance_minor');$t->bigInteger('closing_balance_minor');$t->string('status',20)->default('draft');$t->foreignUlid('prepared_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignUlid('completed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->unique(['cooperative_bank_account_id','statement_start_date','statement_end_date'],'bank_reconciliation_period_unique');});
  Schema::create('bank_statement_lines',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_reconciliation_id')->constrained()->cascadeOnDelete();$t->date('transaction_date');$t->string('reference')->nullable();$t->text('description');$t->bigInteger('amount_minor');$t->bigInteger('running_balance_minor')->nullable();$t->string('external_id')->nullable();$t->string('status',20)->default('unmatched');$t->timestamps();$t->unique(['bank_reconciliation_id','external_id']);});
  Schema::create('bank_reconciliation_matches',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('bank_statement_line_id')->constrained()->cascadeOnDelete();$t->foreignUlid('journal_entry_line_id')->constrained()->cascadeOnDelete();$t->unsignedBigInteger('matched_amount_minor');$t->string('match_type',20)->default('manual');$t->foreignUlid('matched_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('matched_at');$t->unique(['bank_statement_line_id','journal_entry_line_id'],'bank_statement_journal_match_unique');});
 }
 public function down():void{foreach(['bank_reconciliation_matches','bank_statement_lines','bank_reconciliations','cooperative_bank_accounts','accounting_posting_rules','journal_entry_lines','journal_entries','accounting_periods','ledger_accounts'] as $table)Schema::dropIfExists($table);}
};
