<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('loan_applications',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('member_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_product_id')->constrained()->cascadeOnDelete();$t->foreignUlid('approval_workflow_id')->nullable()->constrained()->nullOnDelete();$t->string('reference',80);$t->unsignedBigInteger('requested_principal_minor');$t->unsignedSmallInteger('tenure');$t->text('purpose');$t->string('status',30)->default('draft');$t->foreignUlid('preferred_bank_account_id')->nullable()->constrained('member_bank_accounts')->nullOnDelete();$t->json('applicant_snapshot');$t->json('policy_snapshot')->nullable();$t->unsignedSmallInteger('current_approval_sequence')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamp('rejected_at')->nullable();$t->foreignUlid('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['cooperative_id','reference']);$t->index(['cooperative_id','member_id','status']);});
  Schema::create('loan_assessments',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_application_id')->constrained()->cascadeOnDelete();$t->json('facts');$t->json('eligibility_result');$t->json('policy_result');$t->json('schedule_preview');$t->json('charge_preview');$t->text('recommendation')->nullable();$t->foreignUlid('assessed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('assessed_at');$t->timestamps();});
  Schema::create('loan_application_guarantors',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_application_id')->constrained()->cascadeOnDelete();$t->foreignUlid('guarantor_member_id')->constrained('members')->cascadeOnDelete();$t->unsignedBigInteger('guaranteed_amount_minor');$t->json('capacity_snapshot');$t->string('status',20)->default('pending');$t->timestamp('consented_at')->nullable();$t->timestamps();$t->unique(['loan_application_id','guarantor_member_id']);});
  Schema::create('loan_approval_decisions',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_application_id')->constrained()->cascadeOnDelete();$t->foreignUlid('approval_workflow_step_id')->constrained()->cascadeOnDelete();$t->foreignUlid('actor_id')->constrained('users')->cascadeOnDelete();$t->string('decision',20);$t->text('comment')->nullable();$t->timestamp('decided_at');$t->unique(['loan_application_id','approval_workflow_step_id','actor_id'],'loan_decision_actor_step_unique');});
  Schema::create('loans',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_application_id')->unique()->constrained()->cascadeOnDelete();$t->foreignUlid('member_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_product_id')->constrained()->cascadeOnDelete();$t->string('loan_number',80);$t->unsignedBigInteger('principal_minor');$t->unsignedBigInteger('interest_minor');$t->unsignedBigInteger('charges_added_minor')->default(0);$t->unsignedBigInteger('repayable_minor');$t->unsignedBigInteger('outstanding_minor');$t->string('status',30)->default('active');$t->date('disbursed_at');$t->date('maturity_date');$t->timestamps();$t->unique(['cooperative_id','loan_number']);$t->index(['cooperative_id','member_id','status']);});
  Schema::create('loan_charges',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->constrained()->cascadeOnDelete();$t->foreignUlid('charge_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('treatment',30);$t->unsignedBigInteger('amount_minor');$t->json('snapshot');$t->timestamps();});
  Schema::create('loan_repayment_installments',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->constrained()->cascadeOnDelete();$t->unsignedSmallInteger('installment_number');$t->date('due_date');$t->unsignedBigInteger('principal_due_minor');$t->unsignedBigInteger('interest_due_minor');$t->unsignedBigInteger('charges_due_minor')->default(0);$t->unsignedBigInteger('amount_paid_minor')->default(0);$t->string('status',20)->default('upcoming');$t->timestamps();$t->unique(['loan_id','installment_number']);$t->index(['cooperative_id','due_date','status']);});
  Schema::create('payout_batches',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->string('reference',80);$t->string('idempotency_key',120);$t->string('name');$t->string('type',40)->default('bulk');$t->unsignedInteger('item_count')->default(0);$t->unsignedBigInteger('total_amount_minor')->default(0);$t->string('status',30)->default('draft');$t->foreignUlid('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['cooperative_id','reference']);$t->unique(['cooperative_id','idempotency_key']);});
  Schema::create('payouts',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('payout_batch_id')->nullable()->constrained()->nullOnDelete();$t->foreignUlid('member_id')->nullable()->constrained()->nullOnDelete();$t->string('payable_type')->nullable();$t->ulid('payable_id')->nullable();$t->string('reference',100);$t->string('idempotency_key',120);$t->string('type',40);$t->string('currency',3)->default('NGN');$t->unsignedBigInteger('amount_minor');$t->string('beneficiary_name');$t->string('bank_code',20)->nullable();$t->text('account_number_encrypted')->nullable();$t->string('account_number_last_four',4)->nullable();$t->timestamp('scheduled_for')->nullable();$t->string('recurrence_rule')->nullable();$t->string('status',30)->default('draft');$t->string('provider')->nullable();$t->string('provider_reference')->nullable();$t->text('failure_reason')->nullable();$t->foreignUlid('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignUlid('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignUlid('released_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('released_at')->nullable();$t->timestamp('paid_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['cooperative_id','reference']);$t->unique(['cooperative_id','idempotency_key']);$t->index(['cooperative_id','status','scheduled_for']);});
  Schema::create('payout_events',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('payout_id')->constrained()->cascadeOnDelete();$t->string('event_type',40);$t->string('provider_event_id')->nullable();$t->json('payload')->nullable();$t->timestamp('occurred_at');$t->unique(['cooperative_id','provider_event_id']);});
 }
 public function down():void{foreach(['payout_events','payouts','payout_batches','loan_repayment_installments','loan_charges','loans','loan_approval_decisions','loan_application_guarantors','loan_assessments','loan_applications'] as $table)Schema::dropIfExists($table);}
};
