<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::table('loan_repayment_installments',function(Blueprint $t):void{$t->unsignedBigInteger('principal_paid_minor')->default(0)->after('amount_paid_minor');$t->unsignedBigInteger('interest_paid_minor')->default(0);$t->unsignedBigInteger('charges_paid_minor')->default(0);$t->unsignedBigInteger('penalties_due_minor')->default(0);$t->unsignedBigInteger('penalties_paid_minor')->default(0);$t->unsignedBigInteger('recovery_expenses_due_minor')->default(0);$t->unsignedBigInteger('recovery_expenses_paid_minor')->default(0);$t->date('overdue_since')->nullable();});
  Schema::create('loan_repayments',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->constrained()->cascadeOnDelete();$t->foreignUlid('member_id')->constrained()->cascadeOnDelete();$t->foreignUlid('reversal_of_id')->nullable()->constrained('loan_repayments')->nullOnDelete();$t->string('reference',100);$t->string('idempotency_key',120);$t->string('channel',40);$t->string('currency',3)->default('NGN');$t->unsignedBigInteger('amount_minor');$t->unsignedBigInteger('allocated_minor')->default(0);$t->unsignedBigInteger('unallocated_minor')->default(0);$t->string('status',20)->default('successful');$t->string('external_reference')->nullable();$t->timestamp('received_at');$t->foreignUlid('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->text('notes')->nullable();$t->timestamp('reversed_at')->nullable();$t->foreignUlid('reversed_by')->nullable()->constrained('users')->nullOnDelete();$t->text('reversal_reason')->nullable();$t->timestamps();$t->unique(['cooperative_id','reference']);$t->unique(['cooperative_id','idempotency_key']);$t->index(['cooperative_id','loan_id','received_at']);});
  Schema::create('loan_repayment_allocations',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_repayment_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_repayment_installment_id')->constrained()->cascadeOnDelete();$t->string('component',20);$t->unsignedBigInteger('amount_minor');$t->timestamp('created_at')->useCurrent();$t->index(['loan_repayment_installment_id','component'],'repayment_allocation_installment_component_idx');});
  Schema::create('loan_penalty_applications',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_repayment_installment_id')->constrained()->cascadeOnDelete();$t->foreignUlid('charge_id')->nullable()->constrained()->nullOnDelete();$t->date('assessment_date');$t->unsignedBigInteger('basis_amount_minor');$t->unsignedBigInteger('amount_minor');$t->string('status',20)->default('applied');$t->json('rule_snapshot');$t->foreignUlid('waived_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('waived_at')->nullable();$t->text('waiver_reason')->nullable();$t->timestamps();$t->unique(['loan_repayment_installment_id','charge_id','assessment_date'],'loan_penalty_daily_unique');});
  Schema::create('loan_restructures',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->constrained()->cascadeOnDelete();$t->string('reference',100);$t->text('reason');$t->string('status',20)->default('pending');$t->unsignedBigInteger('capitalized_arrears_minor')->default(0);$t->unsignedInteger('new_interest_rate_basis_points')->nullable();$t->string('new_repayment_frequency',20)->nullable();$t->unsignedSmallInteger('new_tenure');$t->date('new_start_date');$t->json('old_schedule_snapshot');$t->json('new_schedule_snapshot');$t->foreignUlid('requested_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignUlid('decided_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('decided_at')->nullable();$t->text('decision_reason')->nullable();$t->timestamp('applied_at')->nullable();$t->timestamps();$t->unique(['cooperative_id','reference']);});
  Schema::create('loan_recovery_cases',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_id')->unique()->constrained()->cascadeOnDelete();$t->foreignUlid('member_id')->constrained()->cascadeOnDelete();$t->string('reference',100);$t->string('status',30)->default('open');$t->unsignedSmallInteger('days_past_due');$t->unsignedBigInteger('arrears_minor');$t->foreignUlid('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->date('promise_date')->nullable();$t->unsignedBigInteger('promise_amount_minor')->nullable();$t->timestamp('opened_at');$t->timestamp('resolved_at')->nullable();$t->timestamps();$t->unique(['cooperative_id','reference']);});
  Schema::create('loan_recovery_actions',function(Blueprint $t):void{$t->ulid('id')->primary();$t->foreignUlid('cooperative_id')->constrained()->cascadeOnDelete();$t->foreignUlid('loan_recovery_case_id')->constrained()->cascadeOnDelete();$t->string('type',40);$t->text('notes');$t->timestamp('next_action_at')->nullable();$t->unsignedBigInteger('expense_minor')->default(0);$t->foreignUlid('performed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('performed_at');$t->timestamps();});
 }
 public function down():void{foreach(['loan_recovery_actions','loan_recovery_cases','loan_restructures','loan_penalty_applications','loan_repayment_allocations','loan_repayments'] as $table)Schema::dropIfExists($table);Schema::table('loan_repayment_installments',fn(Blueprint $t)=>$t->dropColumn(['principal_paid_minor','interest_paid_minor','charges_paid_minor','penalties_due_minor','penalties_paid_minor','recovery_expenses_due_minor','recovery_expenses_paid_minor','overdue_since']));}
};
