<?php
namespace App\Models;
use App\Enums\InterestMethod; use App\Enums\RepaymentFrequency; use App\Models\Concerns\BelongsToTenant; use App\Models\Concerns\HasAuditTrail; use Illuminate\Database\Eloquent\Concerns\HasUlids; use Illuminate\Database\Eloquent\Factories\HasFactory; use Illuminate\Database\Eloquent\Model; use Illuminate\Database\Eloquent\Relations\BelongsTo; use Illuminate\Database\Eloquent\Relations\BelongsToMany; use Illuminate\Database\Eloquent\Relations\HasMany; use Illuminate\Database\Eloquent\SoftDeletes;
class LoanProduct extends Model
{
    use BelongsToTenant, HasAuditTrail, HasFactory, HasUlids, SoftDeletes;
    protected $fillable = ['cooperative_id','approval_workflow_id','name','code','description','minimum_principal_minor','maximum_principal_minor','minimum_tenure','maximum_tenure','interest_method','annual_interest_rate_basis_points','repayment_frequency','grace_period_days','moratorium_periods','requires_guarantors','minimum_guarantors','maximum_guarantors','maximum_debt_to_income_basis_points','contribution_limit_multiplier_basis_points','savings_limit_multiplier_basis_points','minimum_membership_months','guarantor_maximum_exposure_basis_points','guarantor_maximum_active_loans','allows_early_settlement','is_active','configuration'];
    protected function casts(): array { return ['interest_method'=>InterestMethod::class,'repayment_frequency'=>RepaymentFrequency::class,'minimum_principal_minor'=>'integer','maximum_principal_minor'=>'integer','minimum_tenure'=>'integer','maximum_tenure'=>'integer','annual_interest_rate_basis_points'=>'integer','grace_period_days'=>'integer','moratorium_periods'=>'integer','requires_guarantors'=>'boolean','minimum_guarantors'=>'integer','maximum_guarantors'=>'integer','maximum_debt_to_income_basis_points'=>'integer','contribution_limit_multiplier_basis_points'=>'integer','savings_limit_multiplier_basis_points'=>'integer','minimum_membership_months'=>'integer','guarantor_maximum_exposure_basis_points'=>'integer','guarantor_maximum_active_loans'=>'integer','allows_early_settlement'=>'boolean','is_active'=>'boolean','configuration'=>'array']; }
    public function charges(): BelongsToMany { return $this->belongsToMany(Charge::class,'loan_product_charges')->withPivot(['sequence','is_mandatory','overrides'])->withTimestamps()->orderByPivot('sequence'); }
    public function eligibilityRules(): HasMany { return $this->hasMany(LoanProductEligibilityRule::class)->orderBy('sequence'); }
    public function approvalWorkflow(): BelongsTo { return $this->belongsTo(ApprovalWorkflow::class); }
}
